name: RTea
version: '${project.version}'
main: me.pluginrawtea.rtea.RTea
api-version: '1.20'
commands:
  followblockmode:
    description: A block will spawn underneath you wherever you go
    usage: /<command>
    permission: rtea.FollowingSpawnBlock
  bitz:
    description: balance stuff
  ibr:
    description: Ipans breaking record.
  ibrm:
    description: Ipans breaking record moment.
  gchat:
    description: Toggles groupchat /g.